Repository spdx/spdx-3-model, pull requests merged in 2024-04, with the labels that each got.

#688 Clarify meaning of empty copyrightText string
  model/Software/Properties/copyrightText.md
Labels: Profile:Licensing

#681 Update autonomyType.md
  model/AI/Properties/autonomyType.md
Labels: Profile:AI

#663 Update service profile for use case 9
  model/Service/Classes/SoftwareService.md
  model/Service/Properties/serverAuthenticationProtocol.md
  model/Service/Vocabularies/AuthenticationProtocolType.md
Labels: profile:service

#692 Update AIPackage.md
  model/AI/Classes/AIPackage.md
Labels: Profile:AI

#683 AI: Update safetyRiskAssessment description
  model/AI/Properties/safetyRiskAssessment.md
  model/AI/Vocabularies/SafetyRiskAssessmentType.md
Labels: Profile:AI

#687 Reference License Expressions annex and cleanup
  model/SimpleLicensing/Classes/LicenseExpression.md
  model/SimpleLicensing/Properties/customIdToUri.md
  model/SimpleLicensing/Properties/licenseExpression.md
  model/SimpleLicensing/SimpleLicensing.md
Labels: Profile:Licensing

#693 Update DatasetPackage.md
  model/Dataset/Classes/DatasetPackage.md
Labels: Profile:Dataset

#672 Proposed extension classes to support CDX properties
  model/Core/Classes/NamespaceMap.md
  model/Extension/Classes/CdxPropertiesExtension.md
  model/Extension/Classes/CdxPropertyEntry.md
  model/Extension/Properties/cdxPropName.md
  model/Extension/Properties/cdxPropValue.md
  model/Extension/Properties/cdxProperty.md
Labels: enhancement

#697 Changes to AI profile to accommodate expressing energyConsumption
  model/AI/Classes/EnergyConsumption.md
  model/AI/Classes/EnergyConsumptionDescription.md
  model/AI/Properties/energyConsumption.md
  model/AI/Properties/energyQuantity.md
  model/AI/Properties/energyUnit.md
  model/AI/Properties/finetuningEnergyConsumption.md
  model/AI/Properties/inferenceEnergyConsumption.md
  model/AI/Properties/trainingEnergyConsumption.md
  model/AI/Vocabularies/EnergyUnitType.md
Labels: Profile:AI

#644 Update EpssVulnAssessmentRelationship.md
  model/Security/Classes/EpssVulnAssessmentRelationship.md
Labels: Profile:Security

#715 Change gitoid to contentIdentifier in PackageVerificationCode
  model/Core/Classes/PackageVerificationCode.md
Labels: Profile:Core

#609 Updates integrity verification docs in Core
  model/Core/Classes/Hash.md
  model/Core/Classes/IntegrityMethod.md
  model/Core/Properties/verifiedUsing.md
Labels: Profile:Software
