Repository spdx/spdx-3-model, pull requests merged in 2025-03, with the labels that each got.

#966 Software: Add sizeInBytes in field
  model/Software/Classes/SoftwareArtifact.md
  model/Software/Properties/artifactSize.md
Labels: Profile:Core

#1003 fix link to RFC 3696
  model/Core/Vocabularies/ExternalIdentifierType.md
Labels: Profile:Core, typo

#994 VulnAssessmentRelationship example fixes
  model/Security/Classes/CvssV2VulnAssessmentRelationship.md
  model/Security/Classes/CvssV3VulnAssessmentRelationship.md
  model/Security/Classes/CvssV4VulnAssessmentRelationship.md
  model/Security/Classes/EpssVulnAssessmentRelationship.md
  model/Security/Classes/ExploitCatalogVulnAssessmentRelationship.md
  model/Security/Classes/SsvcVulnAssessmentRelationship.md
  model/Security/Classes/VexAffectedVulnAssessmentRelationship.md
  model/Security/Classes/VexFixedVulnAssessmentRelationship.md
  model/Security/Classes/VexNotAffectedVulnAssessmentRelationship.md
  model/Security/Classes/VexUnderInvestigationVulnAssessmentRelationship.md
  model/Security/Classes/VexVulnAssessmentRelationship.md
  model/Security/Classes/Vulnerability.md
Labels: examples, Profile:Security, typo

#1004 fix kilowatt-hour typo
  model/AI/Classes/EnergyConsumptionDescription.md
Labels: Profile:AI, typo

#972 Add spec-parser usage to Markdown formatting document
  Contributing.md
  docs/format.md
Labels: documentation

#1002 Remove the ServiceProvider class
  model/Service/Classes/ServiceProvider.md
  model/Service/Classes/SoftwareService.md
Labels: profile:Service

#1006 Fix email RFC link in ExternalIdentifierType vocab
  model/Core/Vocabularies/ExternalIdentifierType.md
Labels: Profile:Core

#1007 Fix kilowatt-hour value typo in EnergyConsumptionDescription
  model/AI/Classes/EnergyConsumptionDescription.md
Labels: Profile:AI

#951 Add Chinese translation for models - Part IV
  model/Extension/Classes/CdxPropertiesExtension.md
  model/Extension/Classes/CdxPropertyEntry.md
  model/Extension/Classes/Extension.md
  model/Extension/Extension.md
  model/Extension/Properties/cdxPropName.md
  model/Extension/Properties/cdxPropValue.md
  model/Extension/Properties/cdxProperty.md
  model/Licensing/Licensing.md
  model/Lite/Lite.md
  model/Security/Classes/CvssV2VulnAssessmentRelationship.md
  model/Security/Classes/CvssV3VulnAssessmentRelationship.md
  model/Security/Classes/CvssV4VulnAssessmentRelationship.md
  model/Security/Classes/EpssVulnAssessmentRelationship.md
  model/Security/Classes/ExploitCatalogVulnAssessmentRelationship.md
  model/Security/Classes/SsvcVulnAssessmentRelationship.md
  model/Security/Classes/VexAffectedVulnAssessmentRelationship.md
  model/Security/Classes/VexFixedVulnAssessmentRelationship.md
  model/Security/Classes/VexNotAffectedVulnAssessmentRelationship.md
  model/Security/Classes/VexUnderInvestigationVulnAssessmentRelationship.md
  model/Security/Classes/VexVulnAssessmentRelationship.md
  model/Security/Classes/VulnAssessmentRelationship.md
  model/Security/Classes/Vulnerability.md
  model/Security/Properties/actionStatement.md
  model/Security/Properties/actionStatementTime.md
  model/Security/Properties/assessedElement.md
  model/Security/Properties/catalogType.md
  model/Security/Properties/decisionType.md
  model/Security/Properties/exploited.md
  model/Security/Properties/impactStatement.md
  model/Security/Properties/impactStatementTime.md
  model/Security/Properties/justificationType.md
  model/Security/Properties/locator.md
  model/Security/Properties/modifiedTime.md
  model/Security/Properties/percentile.md
  model/Security/Properties/probability.md
  model/Security/Properties/publishedTime.md
  model/Security/Properties/score.md
  model/Security/Properties/severity.md
  model/Security/Properties/statusNotes.md
  model/Security/Properties/vectorString.md
  model/Security/Properties/vexVersion.md
  model/Security/Properties/withdrawnTime.md
  model/Security/Security.md
  model/Security/Vocabularies/CvssSeverityType.md
  model/Security/Vocabularies/ExploitCatalogType.md
  model/Security/Vocabularies/SsvcDecisionType.md
  model/Security/Vocabularies/VexJustificationType.md
Labels: Translation:zh-Hans

#952 Add Chinese translation for models - Part V
  model/SimpleLicensing/Classes/AnyLicenseInfo.md
  model/SimpleLicensing/Classes/LicenseExpression.md
  model/SimpleLicensing/Classes/SimpleLicensingText.md
  model/SimpleLicensing/Properties/customIdToUri.md
  model/SimpleLicensing/Properties/licenseExpression.md
  model/SimpleLicensing/Properties/licenseListVersion.md
  model/SimpleLicensing/Properties/licenseText.md
  model/SimpleLicensing/SimpleLicensing.md
  model/Software/Classes/ContentIdentifier.md
  model/Software/Classes/File.md
  model/Software/Classes/Package.md
  model/Software/Classes/Sbom.md
  model/Software/Classes/Snippet.md
  model/Software/Classes/SoftwareArtifact.md
  model/Software/Properties/additionalPurpose.md
  model/Software/Properties/attributionText.md
  model/Software/Properties/byteRange.md
  model/Software/Properties/contentIdentifier.md
  model/Software/Properties/contentIdentifierType.md
  model/Software/Properties/contentIdentifierValue.md
  model/Software/Properties/copyrightText.md
  model/Software/Properties/downloadLocation.md
  model/Software/Properties/fileKind.md
  model/Software/Properties/homePage.md
  model/Software/Properties/lineRange.md
  model/Software/Properties/packageUrl.md
  model/Software/Properties/packageVersion.md
  model/Software/Properties/primaryPurpose.md
  model/Software/Properties/sbomType.md
  model/Software/Properties/snippetFromFile.md
  model/Software/Properties/sourceInfo.md
  model/Software/Software.md
  model/Software/Vocabularies/ContentIdentifierType.md
  model/Software/Vocabularies/FileKindType.md
  model/Software/Vocabularies/SbomType.md
  model/Software/Vocabularies/SoftwarePurpose.md
Labels: Translation:zh-Hans
